-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 17:13:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema santadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema santadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `santadb` DEFAULT CHARACTER SET utf8 ;
USE `santadb` ;

-- -----------------------------------------------------
-- Table `santadb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `santadb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` CHAR(20) NULL,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `email` VARCHAR(90) NULL,
  `password` VARCHAR(45) NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santadb`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `santadb`.`calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `guid` VARCHAR(45) NULL,
  `detail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santadb`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `santadb`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture` VARCHAR(255) NULL,
  `detail` MEDIUMTEXT NULL,
  `date` DATETIME NULL,
  `user_id` INT NOT NULL,
  `calendar_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `calendar_id`),
  UNIQUE INDEX `picture_UNIQUE` (`picture` ASC),
  INDEX `fk_action_user_idx` (`user_id` ASC),
  INDEX `fk_action_calendar1_idx` (`calendar_id` ASC),
  CONSTRAINT `fk_action_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `santadb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `santadb`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santadb`.`user_has_calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `santadb`.`user_has_calendar` (
  `user_id` INT NOT NULL,
  `calendar_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `calendar_id`),
  INDEX `fk_user_has_calendar_calendar1_idx` (`calendar_id` ASC),
  INDEX `fk_user_has_calendar_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_calendar_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `santadb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_calendar_calendar1`
    FOREIGN KEY (`calendar_id`)
    REFERENCES `santadb`.`calendar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
